json.id pantry_item.id
json.ingredient_id pantry_item.ingredient_id
json.user_id pantry_item.user_id
json.amount pantry_item.amount
json.category pantry_item.category
json.name pantry_item.ingredient&.name
json.image_url pantry_item.ingredient&.image_url
json.use_by_date pantry_item.use_by_date
json.created_at pantry_item.created_at
json.updated_at pantry_item.updated_at
